name: MHR Utilities (one file)

on:
  workflow_dispatch:

env:
  VersionMarjor: 2
  VersionMinor: ${{ github.run_number }}
  # VersionBuild: ${{ github.run_id }}
  VersionBuild: 0
  VersionRevision: ${{ github.run_attempt }}
  ArtifactBaseName: MHR_Util
  BuildScript: build\scripts\buildExeOneFile.bat
  PrebuildScript: build\scripts\prebuild.py
  VersionFile: build\version_info.txt
  ArtifactFolder: dist\
  PythonRequirements: build\python_requirements.txt

jobs:
  build_release:
    runs-on: windows-latest

    steps:
      - name: Set Full Version
        run: |
          echo ("FullVersion=${{ env.VersionMarjor }}.${{ env.VersionMinor }}.${{ env.VersionBuild }}.${{ env.VersionRevision }}") >> $env:GITHUB_ENV

      - name: Set artifact name
        run: |
          echo ("ArtifactName=${{ env.ArtifactBaseName }}") >> $env:GITHUB_ENV

      - name: Set artifact path (one file)
        run: |
          echo ("ArtifactFullPath=${{ env.ArtifactFolder }}/${{ env.ArtifactName }}.exe") >> $env:GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 1    

      - name: Read Python version
        id: python_version
        shell: bash
        run: echo "PythonVersion=$(<.python-version)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PythonVersion }}
          cache: 'pip'
          cache-dependency-path: ${{ env.PythonRequirements }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.PythonRequirements }}
          
      - name: Run prebuild
        run: |
          python "${{ env.PrebuildScript }}" "${{ env.ArtifactName }}" "${{ env.VersionMarjor }}" "${{ env.VersionMinor }}" "${{ env.VersionBuild }}" "${{ env.VersionRevision }}" ${{ env.VersionFile }}

      - name: Create EXE (one file)
        run: |
          .\${{ env.BuildScript }} "${{ env.ArtifactName }}" "${{ env.VersionFile }}"

      - name: Upload artifact (one file)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ArtifactName }} 
          path: |
            ${{ env.ArtifactFullPath }}

      - name: Build preprelease
        if: ${{ !startsWith(github.ref, 'refs/heads/release/') }}
        run: |
          echo ("PRERELEASE=true") >> $env:GITHUB_ENV

      - name: Build tag name
        if: ${{ env.PRERELEASE == 'true' }}
        run: |
          echo FullVersion=${FullVersion}-prerelease >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ env.FullVersion }}
          generate_release_notes: true
          name: ${{ env.ArtifactName }} (Compressed)
          prerelease: ${{ env.PRERELEASE == 'true' }}
          # make_latest: ${{ env.PRERELEASE != 'true' }}
          files: |
            ${{ env.ArtifactFullPath }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          

      - name: Delete pre-release
        if: ${{ env.PRERELEASE != 'true' }}
        uses: jluo1996/delete-releases-action@v1
        with:
            tag-pattern: "*-prerelease*"
            keep-latest: 0
            remove-tags: true
            repository: ${{ github.repository }}
            token: ${{ secrets.GITHUB_TOKEN }}
